openapi: 3.0.1
info:
  title: Heals BE 2.0 Appointment API
  description: >-
    API specification for eHealth Transaction API


    - Query parameters - Multiple values for the same parameter name are passed
    as separate params, i.e. /Appointment?date=ge2010-01-01&date=le2011-12-31
  contact: {}
  version: v0.0.18
servers:
  - url: /fhir
    variables: {}
tags:
  - name: PractitionerRole
    description: >-
      Please check
      '[PractitionerRole](https://www.hl7.org/fhir/practitionerrole.html)'
      specification.
paths:
  /PractitionerRole:
    get:
      summary: Search PractitionerRoles
      tags:
        - PractitionerRole
      description: >-
        This endpoint is used to search for PractitionRoles. Related resources
        like the Location, Practiotioner, Organization, etc. might also be
        returned by this endpoint.
      operationId: SubmitTransaction
      parameters:
        - name: _include
          in: query
          description: The resources to include into response.
          required: false
          schema:
            type: string
            enum:
              - Practitioner
              - Organization
            example: Practitioner
        - name: _revinclude
          in: query
          description: The resources to include into response (reverse include).
          required: false
          schema:
            type: string
            enum:
              - Location.managingOrganization
            example: Location.managingOrganization
        - name: northeast-longitude
          in: query
          description: The northeast longtitude.
          required: false
          schema:
            type: number
            format: double
            example: 114.1858
        - name: northeast-latitude
          in: query
          description: The northeast latitude.
          required: false
          schema:
            type: number
            format: double
            example: 114.1858
        - name: southwest-longitude
          in: query
          description: The southwest longtitude.
          required: false
          schema:
            type: number
            format: double
            example: 114.1858
        - name: southwest-latitude
          in: query
          description: The southwest latitude.
          required: false
          schema:
            type: number
            format: double
            example: 114.1858
        - name: Practitioner.specialty
          in: query
          description: The practitioner specialty.
          required: false
          schema:
            type: string
            example: >-
              http://healshealthcare.com/fhir/CodeSystem/practitioner-specialty|family-doctor
        - name: Content-Type
          in: header
          description: The content type.
          required: true
          schema:
            type: string
            example: application/json
      responses:
        '200':
          description: Content-Type.
          headers:
            Content-Type:
              schema:
                type: string
                example: application/json
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Bundle'
              examples:
                successful:
                  $ref: '#/components/examples/Bundle'
        '400':
          description: Bad Request.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OperationOutcome'
              example:
                resourceType: OperationOutcome
                issue:
                  - code: MSG_PARAM_UNKNOWN
                    details:
                      coding:
                        - system: >-
                            http:/healthhealthcare.com/fhir/ValueSet/operation-outcome
                          code: structure
                      text: Unrecognized query parameter "other"
components:
  schemas:
    OperationOutcome:
      description: >-
        See FHIR
        '[OperationOutcome](https://www.hl7.org/fhir/operationoutcome.html)'
      type: object
      properties:
        resourceType:
          type: string
          minLength: 1
        issue:
          type: array
          uniqueItems: true
          minItems: 1
          items:
            required:
              - severity
              - code
            properties:
              severity:
                type: string
                minLength: 1
                description: Issue severity.
              code:
                type: string
                minLength: 1
                description: Error or warning code.
              details:
                $ref: '#/components/schemas/CodeableConcept'
                description: Additional diagnostic information about the issue
          description: Issues associated with the action
      required:
        - resourceType
      example:
        resourceType: OperationOutcome
        issue:
          - severity: error
            code: structure
            details:
              coding:
                - system: 'http://ehealth.ua/fhir/ValueSet/operation-outcome'
                  code: structure
              text: >-
                Profile
                http://ehealth.ua/fhir/StructureDefinition/TransactionBundle,
                Element 'entry': minimum required = 1, but only found 0
    Quantity:
      title: Quantity
      type: object
      properties:
        value:
          type: number
          example: 0
        comparator:
          type: string
          example: '>'
        unit:
          type: string
          description: for future use
          example: mg
        system:
          type: string
          example: eHealth/units
        code:
          type: string
          example: mg
      required:
        - value
        - system
        - code
      example:
        value: 0
        comparator: '>'
        unit: mg
        system: eHealth/units
        code: mg
    Range:
      title: Range
      type: object
      properties:
        low:
          $ref: '#/components/schemas/Quantity'
        high:
          $ref: '#/components/schemas/Quantity'
    Period:
      title: Period
      description: 'See FHIR ''[Period](https://www.hl7.org/fhir/datatypes.html#Period)'''
      type: object
      properties:
        start:
          type: string
          format: datetime
          description: Starting time with inclusive boundary.
        end:
          type: string
          format: datetime
          description: 'End time with inclusive boundary, if not ongoing.'
    Meta:
      title: Meta
      description: 'See FHIR ''[Meta](https://www.hl7.org/fhir/resource.html#Meta)'''
      type: object
      properties:
        profile:
          type: array
          items:
            type: string
          description: The StructureDefinition to validate against.
      required:
        - profile
    Identifier:
      title: Identifier
      description: >-
        See FHIR
        '[Identifier](https://www.hl7.org/fhir/datatypes.html#Identifier)'.
        Custom profile for Identifier is used - system and value are required.
      type: object
      properties:
        system:
          type: string
          description: The namespace for the identifier value.
        value:
          type: string
          description: The value that is unique.
      required:
        - system
        - value
    Reference:
      title: Reference
      description: >-
        See FHIR
        '[Reference](https://www.hl7.org/fhir/references.html#Reference)'.
        Reference should be either literal ("reference" is required), or logical
        ("identifier" is required)
      type: object
      properties:
        reference:
          type: string
          description: 'Literal reference, Relative, internal or absolute URL.'
        type:
          type: string
          description: Type the reference refers to (e.g. "Observation")
        identifier:
          $ref: '#/components/schemas/Identifier'
      required:
        - reference
      example:
        reference: >-
          http://ehealth.ua/fhir/Observation/9183a36b-4d45-4244-9339-63d81cd08d9c
        type: Observation
    CodeableConcept:
      title: CodeableConcept
      description: >-
        See FHIR
        '[CodeableConcept](https://www.hl7.org/fhir/datatypes.html#CodeableConcept)'
      type: object
      properties:
        coding:
          type: array
          items:
            $ref: '#/components/schemas/Coding'
          description: ''
        text:
          type: string
      required:
        - coding
    Coding:
      title: Coding
      description: 'See FHIR ''[Coding](https://www.hl7.org/fhir/datatypes.html#Coding)'''
      type: object
      properties:
        system:
          type: string
          description: Identity of the terminology system
        code:
          type: string
          description: Symbol in syntax defined by the system
      required:
        - system
        - code
      example:
        system: eHealth/encounter_classes
        code: AMB
    Encounter:
      title: Encounter
      description: 'See FHIR ''[Encounter](https://www.hl7.org/fhir/encounter.html)'''
      required:
        - meta
        - resourceType
        - id
        - class
        - subject
        - status
      type: object
      properties:
        resourceType:
          type: string
          description: The resource type.
        id:
          type: string
          description: Id of the resource.
        meta:
          type: object
          properties:
            profile:
              type: array
              items:
                $ref: '#/components/schemas/Reference'
        status:
          type: string
          description: >-
            CodeSystem
            http://ehealth.edenlabllc.com/CodeSystem/eHealth/encounter_statuses
        class:
          $ref: '#/components/schemas/Coding'
        date:
          type: string
          format: datetime
        subject:
          $ref: '#/components/schemas/Reference'
        participant:
          type: array
          items:
            type: object
            properties:
              type:
                $ref: '#/components/schemas/CodeableConcept'
              period:
                $ref: '#/components/schemas/Period'
              individual:
                $ref: '#/components/schemas/Reference'
        episodeOfCare:
          $ref: '#/components/schemas/Reference'
        basedOn:
          $ref: '#/components/schemas/Reference'
        type:
          $ref: '#/components/schemas/CodeableConcept'
        serviceProvider:
          $ref: '#/components/schemas/Reference'
        diagnoses:
          type: array
          items:
            type: object
            properties:
              condition:
                $ref: '#/components/schemas/Reference'
              use:
                $ref: '#/components/schemas/CodeableConcept'
              rank:
                type: number
                description: Ranking of the diagnosis. Max value = 10 (for each role type)
          description: The list of diagnosis relevant to this encounter
        location:
          $ref: '#/components/schemas/Reference'
        hospitalization:
          type: object
          properties:
            admitSource:
              $ref: '#/components/schemas/CodeableConcept'
            reAdmission:
              $ref: '#/components/schemas/CodeableConcept'
        priority:
          $ref: '#/components/schemas/CodeableConcept'
      example:
        resourceType: Encounter
        meta:
          profile:
            - 'http://ehealth.ua/fhir/StructureDefinition/Encounter'
        id: 465fb6fe-2dea-4b8a-9ef7-58379d1eaab0
        subject:
          identifier:
            system: 'https://ehealth.ua/MPI'
            value: f1ee0439-79be-4371-bf61-0b9066525233
        participant:
          - type:
              coding:
                - system: 'http://ehealth.edenlabllc.com/CodeSystem/participant-type'
                  code: PPRF
            individual:
              identifier:
                system: 'https://ehealth.ua/Employees'
                value: 7ff2dc86-d6a6-4989-9682-333638f8344e
        status: finished
        date: 2018-08-02T10:45:16.000Z
        episodeOfCare:
          reference: >-
            http://ehealth.ua/fhir/EpisodeOfCare/9183a36b-4d45-4244-9339-63d81cd08d9c
        basedOn:
          reference: >-
            http://ehealth.ua/fhir/ServiceRequest/9183a36b-4d45-4244-9339-63d81cd08d9c
        class:
          system: 'http://ehealth.ua/fhir/CodeSystem/eHealth/encounter_classes'
          code: PHC
        type:
          coding:
            - system: 'http://ehealth.ua/fhir/CodeSystem/eHealth/encounter_types'
              code: field
        serviceProvider:
          reference: >-
            http://ehealth.ua/fhir/Organization/9183a36b-4d45-4244-9339-63d81cd08d9c
        diagnoses:
          - condition:
              reference: >-
                http://ehealth.ua/fhir/Condition/9183a36b-4d45-4244-9339-63d81cd08d9c
            use:
              coding:
                - system: 'http://ehealth.ua/fhir/CodeSystem/eHealth/diagnosis_roles'
                  code: primary
            rank: 1
        location:
          reference: 'http://ehealth.ua/fhir/Location/9183a36b-4d45-4244-9339-63d81cd08d9c'
        hospitalization:
          admitSource:
            coding:
              - system: >-
                  http://ehealth.ua/fhir/CodeSystem/eHealth/encounter_admit_source
                code: EMD
          reAdmission:
            coding:
              - system: >-
                  http://ehealth.edenlabllc.com/CodeSystem/eHealth/diagnosis_readmission
                code: R
        priority:
          coding:
            - system: >-
                http://ehealth.edenlabllc.com/CodeSystem/eHealth/encounter_priority
              code: R
    HumanName:
      title: HumanName
      description: >-
        See FHIR
        '[HumanName](https://www.hl7.org/fhir/datatypes.html#HumanName)'
      required:
        - use
      type: object
      properties:
        use:
          type: string
          enum:
            - usual
            - official
            - temp
            - nickname
            - anonymous
            - old
            - maiden
          description: 'CodeSystem - http://hl7.org/fhir/name-use'
    Practitioner:
      title: Practitioner
      description: 'See FHIR ''[Practitioner](https://www.hl7.org/fhir/practitioner.html)'''
      required:
        - id
        - meta
        - resourceType
        - name
      type: object
      properties:
        resourceType:
          type: string
        id:
          type: string
        meta:
          type: object
          properties:
            profile:
              type: array
              items:
                $ref: '#/components/schemas/Reference'
        name:
          $ref: '#/components/schemas/HumanName'
    Condition:
      title: Condition
      description: 'See FHIR ''[Condition](https://www.hl7.org/fhir/condition.html)'''
      required:
        - id
        - resourceType
        - encounter
        - recorder
        - asserter
        - code
        - onsetDate
      type: object
      properties:
        resourceType:
          type: string
          example: Condition
        meta:
          type: object
          properties:
            profile:
              type: array
              items:
                $ref: '#/components/schemas/Reference'
        id:
          type: string
          example: 90a9e15b-b71b-4caf-8f2e-ff247e8a5600
        subject:
          $ref: '#/components/schemas/Reference'
        recorder:
          $ref: '#/components/schemas/Reference'
        asserter:
          $ref: '#/components/schemas/Reference'
        code:
          $ref: '#/components/schemas/CodeableConcept'
        clinicalStatus:
          $ref: '#/components/schemas/CodeableConcept'
        verificationStatus:
          $ref: '#/components/schemas/CodeableConcept'
        severity:
          $ref: '#/components/schemas/CodeableConcept'
        bodySites:
          type: array
          items:
            $ref: '#/components/schemas/CodeableConcept'
          description: ''
        onsetDate:
          type: string
          example: 2018-10-08T09:46:37.694Z
        recordedDate:
          type: string
          example: 2018-10-08T09:46:37.694Z
        stage:
          type: object
          properties:
            summary:
              $ref: '#/components/schemas/CodeableConcept'
          required:
            - summary
        evidence:
          type: array
          items:
            type: object
            properties:
              code:
                type: array
                items:
                  $ref: '#/components/schemas/CodeableConcept'
                description: ''
              detail:
                type: array
                items:
                  $ref: '#/components/schemas/Reference'
          description: Supporting evidence
      example:
        resourceType: Condition
        meta:
          profile:
            - 'http://ehealth.ua/fhir/StructureDefinition/Condition'
        id: 90a9e15b-b71b-4caf-8f2e-ff247e8a5600
        subject:
          identifier:
            system: 'https://ehealth.ua/MPI'
            value: f1ee0439-79be-4371-bf61-0b9066525233
        recorder:
          identifier:
            system: 'https://ehealth.ua/Employees'
            value: 7ff2dc86-d6a6-4989-9682-333638f8344e
        asserter:
          identifier:
            system: 'https://ehealth.ua/Employees'
            value: 7ff2dc86-d6a6-4989-9682-333638f8344e
        encounter:
          reference: >-
            http://ehealth.ua/fhir/Encounter/9183a36b-4d45-4244-9339-63d81cd08d9c
        code:
          coding:
            system: 'http://ehealth.ua/fhir/CodeSystem/ICD10'
            code: A00.0
        clinicalStatus:
          coding:
            system: >-
              http://ehealth.ua/fhir/CodeSystem/eHealth/condition_clinical_statuses
            code: active
        verificationStatus:
          coding:
            system: >-
              http://ehealth.ua/fhir/CodeSystem/eHealth/condition_verification_statuses
            code: confirmed
        severity:
          coding:
            system: 'http://ehealth.ua/fhir/CodeSystem/eHealth/condition_severities'
            code: mild
        bodySite:
          coding:
            system: 'http://ehealth.ua/fhir/CodeSystem/eHealth/body_sites'
            code: 106004
        onsetDateTime: 2018-10-08T09:46:37.694Z
        recordedDate: 2018-10-08T09:46:37.694Z
        stage:
          summary:
            coding:
              system: 'http://ehealth.ua/fhir/CodeSystem/eHealth/condition_stages'
              code: 260998006
        evidences:
          code:
            coding:
              system: 'http://ehealth.ua/fhir/CodeSystem/eHealth/ICPC2/reasons'
              code: B41
          detail:
            reference: >-
              http://ehealth.ua/fhir/Observation/9183a36b-4d45-4244-9339-63d81cd08d9c
    ContactPoint:
      title: ContactPoint
      description: >-
        See FHIR
        '[ContactPoint](https://www.hl7.org/fhir/datatypes.html#ContactPoint)'
      type: object
      properties:
        system:
          type: string
          enum:
            - phone
            - fax
            - email
            - pager
            - url
            - sms
            - other
          description: >-
            [ContactPointSystem](https://www.hl7.org/fhir/valueset-contact-point-system.html)
        value:
          type: string
          description: The actual contact point details.
        use:
          type: string
          enum:
            - home
            - work
            - temp
            - old
            - mobile
          description: >-
            [ContactPointUse](https://www.hl7.org/fhir/valueset-contact-point-use.html)
        rank:
          type: integer
          description: Specify preferred order of use (1 = highest).
        period:
          $ref: '#/components/schemas/Period'
    ContactDetail:
      title: ContactDetail
      description: >-
        See FHIR
        '[ContactDetail](https://www.hl7.org/fhir/metadatatypes.html#ContactDetail)'
      type: object
      properties:
        name:
          type: string
          description: Name of an individual to contact.
        telecom:
          $ref: '#/components/schemas/ContactPoint'
    UsageContext:
      title: UsageContext
      description: >-
        See FHIR
        '[UsageContext](https://www.hl7.org/fhir/metadatatypes.html#UsageContext)'
      type: object
      properties:
        code:
          $ref: '#/components/schemas/Coding'
        valueCodeableConcept:
          $ref: '#/components/schemas/CodeableConcept'
        valueQuantity:
          $ref: '#/components/schemas/Quantity'
        valueRange:
          $ref: '#/components/schemas/Range'
        valueReference:
          $ref: '#/components/schemas/Reference'
    ElementDefinition:
      title: ElementDefinition
      type: object
      description: >-
        See FHIR
        '[ElementDefinition](http://www.hl7.org/fhir/elementdefinition.html#ElementDefinition)'
      required:
        - path
      properties:
        path:
          type: string
          description: Path of the element in the hierarchy of elements.
    StructureDefinition:
      title: StructureDefinition
      description: >-
        See FHIR
        '[StructureDefinition](http://www.hl7.org/fhir/structuredefinition.html)'
        and '[profiling](https://www.hl7.org/fhir/profiling.html)'
      required:
        - meta
        - resourceType
        - id
        - url
        - name
        - status
        - kind
        - abstract
        - type
      type: object
      properties:
        resourceType:
          type: string
          description: The resource type.
        id:
          type: string
          description: Id of the resource.
        meta:
          type: object
          properties:
            profile:
              type: array
              items:
                $ref: '#/components/schemas/Reference'
        url:
          type: string
          description: >-
            Canonical identifier for this structure definition, represented as a
            URI (globally unique).
        identifier:
          type: string
          description: Additional identifier for the structure definition.
        version:
          type: string
          description: Business version of the structure definition.
        name:
          type: string
          description: Name for this structure definition (computer friendly).
        title:
          type: string
          description: Name for this structure definition (human friendly).
        status:
          type: string
          enum:
            - draft
            - active
            - retired
            - unknown
          description: The pulication status.
        expertimental:
          type: boolean
          description: 'For testing purposes, not real usage.'
        date:
          type: string
          format: datetime
          description: Date last changed.
        publisher:
          type: string
          description: Name of the publisher (organization or individual).
        contactDetail:
          type: array
          items:
            $ref: '#/components/schemas/ContactDetail'
          description: Contact details for the publisher
        description:
          type: string
          description: Natural language description of the structure definition.
        useContext:
          type: array
          items:
            $ref: '#/components/schemas/UsageContext'
          description: The context that the content is intended to support.
        jurisdiction:
          $ref: '#/components/schemas/CodeableConcept'
        purpose:
          type: string
          description: Why this structure definition is defined.
        copyright:
          type: string
          description: Use and/or publishing restrictions.
        keyword:
          type: array
          items:
            $ref: '#/components/schemas/Coding'
          description: >-
            Assist with indexing and finding. System -
            [UseCodes](http://www.hl7.org/fhir/valueset-definition-use.html).
        fhirVersion:
          type: string
          description: >-
            FHIR Version this StructureDefinition targets. ValueSet -
            [FHIRVersion](http://www.hl7.org/fhir/valueset-FHIR-version.html).
        mapping:
          type: object
          description: External specification that the content is mapped to.
          properties:
            identity:
              type: string
              description: Internal id when this mapping is used.
            uri:
              type: string
              description: Identifies what this mapping refers to.
            name:
              type: string
              description: Names what this mapping refers to.
            comment:
              type: string
              description: 'Versions, Issues, Scope limitations etc.'
            kind:
              type: string
              enum:
                - primitive-type
                - complex-type
                - resource
                - logical
              description: >-
                [Structure Definition
                Kind](http://www.hl7.org/fhir/valueset-structure-definition-kind.html)
          required:
            - kind
        abstract:
          type: boolean
          description: Whether the structure is abstract.
        context:
          type: object
          description: 'If an extension, where it can be used in instances.'
          required:
            - type
            - expression
          properties:
            type:
              type: string
              enum:
                - fhirpath
                - element
                - extension
              description: >-
                [ExtensionContextType](http://www.hl7.org/fhir/valueset-extension-context-type.html)
            expression:
              type: string
              description: Where the extension can be used in instances.
        contextInvariants:
          type: string
          description: FHIRPath invariants - when the extension can be used.
        type:
          type: string
          description: >-
            Type defined or constrained by this structure.
            [DefinedTypes](http://www.hl7.org/fhir/valueset-defined-types.html)
        baseDefinition:
          type: string
          description: Definition that this type is constrained/specialized from.
        derivation:
          type: string
          enum:
            - specialization
            - constraint
          description: >-
            How relates to base definition.
            [TypeDerivationRule](http://www.hl7.org/fhir/valueset-type-derivation-rule.html).
        snapshot:
          type: object
          description: Snapshot view of the structure.
          required:
            - element
          properties:
            element:
              description: >-
                Definition of elements in the resource (if no
                StructureDefinition).
              type: array
              items:
                $ref: '#/components/schemas/ElementDefinition'
        differential:
          type: object
          description: Differential view of the structure.
          required:
            - element
          properties:
            element:
              description: >-
                Definition of elements in the resource (if no
                StructureDefinition).
              type: array
              items:
                $ref: '#/components/schemas/ElementDefinition'
    Bundle:
      title: Bundle
      description: 'See FHIR ''[Bundle](https://www.hl7.org/fhir/bundle.html)'''
      required:
        - meta
        - resourceType
        - type
        - total
        - entry
      type: object
      properties:
        resourceType:
          type: string
        type:
          type: string
          enum:
            - searchset
          description: The bundle type.
        total:
          type: integer
          description: The total number of matches.
        meta:
          $ref: '#/components/schemas/Meta'
        entry:
          description: Entries (resources) in the bundle.
          type: array
          minItems: 0
          items:
            type: object
            properties:
              fullUrl:
                type: string
                description: URI for resource (Absolute URL server address).
              resource:
                oneOf:
                  - $ref: '#/components/schemas/Encounter'
                  - $ref: '#/components/schemas/Location'
              search:
                description: Search related information.
                type: object
                properties:
                  mode:
                    type: string
                    description: Why this is in the result set.
                    required:
                      - match
                      - include
                      - outcome
                  score:
                    type: number
                    format: float
                    description: Search ranking (between 0 and 1).
    Location:
      title: Location
      description: 'See FHIR ''[Location](https://www.hl7.org/fhir/location.html)'''
      required:
        - id
        - resourceType
        - meta
      type: object
      properties:
        resourceType:
          type: string
          example: Condition
        meta:
          type: object
          properties:
            profile:
              type: array
              items:
                $ref: '#/components/schemas/Reference'
        id:
          type: string
          description: The primary id
        managingOrganization:
          $ref: '#/components/schemas/Reference'
        position:
          type: object
          description: The absolute geographic location
          required:
            - longtitude
            - latitude
          properties:
            longitude:
              type: number
              format: double
              description: Longitude with WGS84 datum
            latitude:
              type: number
              format: double
              description: Latitude with WGS84 datum
    Organization:
      title: Organization
      description: 'See FHIR ''[Organization](https://www.hl7.org/fhir/location.html)'''
      required:
        - id
        - resourceType
        - meta
      type: object
      properties:
        resourceType:
          type: string
          example: Condition
        meta:
          type: object
          properties:
            profile:
              type: array
              items:
                $ref: '#/components/schemas/Reference'
        id:
          type: string
          description: The primary id
        name:
          type: string
          description: Name used for the organization
  examples:
    Location:
      value:
        resourceType: Location
        meta:
          profile:
            - 'http://healshealthcare.com/fhir/StructureDefinition/Location'
        id: 90a9e15b-b71b-4caf-8f2e-ff247e8a5600
        managingOrganization:
          reference: >-
            http://healshealthcare.com/fhir/Organization/9183a36b-4d45-4244-9339-63d81cd08d9c
        position:
          longtitude: 114.1858
          latitude: 22.2772
    Organization:
      value:
        resourceType: Organization
        meta:
          profile:
            - 'http://healshealthcare.com/fhir/StructureDefinition/Organization'
        id: 9183a36b-4d45-4244-9339-63d81cd08d9c
        name:
          longtitude: 114.1858
          latitude: 22.2772
    PractitionerRole:
      value:
        resourceType: PractitionerRole
        meta:
          profile:
            - >-
              http://healshealthcare.com/fhir/StructureDefinition/PractitionerRole
        id: 90a9e15b-b71b-4caf-8f2e-ff247e8a5600
        organization:
          reference: >-
            http://healshealthcare.com/fhir/Organization/9183a36b-4d45-4244-9339-63d81cd08d9c
        practitioner:
          reference: >-
            http://healshealthcare.com/fhir/Practitioner/465fb6fe-2dea-4b8a-9ef7-58379d1eaab0
    Practitioner:
      value:
        resourceType: Practitioner
        meta:
          profile:
            - 'http://healshealthcare.com/fhir/StructureDefinition/Organization'
        id: 465fb6fe-2dea-4b8a-9ef7-58379d1eaab0
        name:
          use: official
          family: Doe
          given:
            - John
          suffix:
            - MD
    Bundle:
      value:
        resourceType: Bundle
        type: searchset
        meta:
          profile:
            - >-
              http://healshealthcare.com/fhir/StructureDefinition/searchset-bundle
        entry:
          - resource:
              $ref: '#/components/examples/Location/value'
            search:
              mode: match
              score: 1
          - resource:
              $ref: '#/components/examples/Organization/value'
            search:
              mode: match
              score: 1
          - resource:
              $ref: '#/components/examples/Practitioner/value'
            search:
              mode: match
              score: 1
